# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json

image: docker.nix-community.org/nixpkgs/cachix-flakes

stages:
  - build
  - push-pages

cache:
  paths:
    - /nix/store

build:
  stage: build
  script:
    - cachix use nix-community
    - cachix use net7toulouse
    - nix build .#docker-stream
    - ./result > docker-image.tar
    - nix profile install nixpkgs#skopeo
    - skopeo login $CI_REGISTRY -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - skopeo --insecure-policy copy "docker-archive:docker-image.tar" "docker://$CI_REGISTRY_IMAGE:latest"

pages:
  stage: push-pages
  only:
    - main
  script:
    - ls public/
  artifacts:
    paths:
      - public
