# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json

image: docker.nix-community.org/nixpkgs/cachix-flakes

stages:
  - build
  - push

cache:
  paths:
    - /nix/store

build:
  stage: build
  script:
    - cachix use net7toulouse
    - nix build .#docker-stream-musl
    - ./result > docker-image.tar
  artifacts:
    paths:
      - docker-image.tar

push:
  stage: push
  script:
    - nix profile install nixpkgs#skopeo
    - skopeo login harbor.k8s.inpt.fr -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD"
    - skopeo --insecure-policy copy "docker-archive:docker-image.tar" "docker://harbor.k8s.inpt.fr/net7_public/churros-online-calendar:latest"
  only:
    - main

pages:
  stage: push
  only:
    - main
  artifacts:
    paths:
      - public